index:
    path: /
    defaults: { _controller: 'App\Controller\LoginController::index' }
register:
    path: /register
    defaults: { _controller: 'App\Controller\LoginController::register' }
logout:
    path: /logout
    defaults: { _controller: 'App\Controller\LoginController::logout' }